# automations.yml - Pool expandido de herramientas de automatización IA
# AUTOMATIZACIÓN CON IA INTEGRADA
- icon: "🤖"
  image: "https://img.youtube.com/vi/QFvKjD1bQ6U/0.jpg"
  title: "Automatiza reportes con Python y Google Sheets"
  link: "https://www.youtube.com/watch?v=QFvKjD1bQ6U"
  desc: "Tutorial paso a paso para generar y enviar reportes automáticos usando Python y Google Sheets API."
  cta: "Ver tutorial"
  category: "data-automation"
- icon: "🤖"
  image: "https://www.make.com/favicon.ico"
  title: "Conecta APIs sin código con Make"
  link: "https://www.make.com/en/"
  desc: "Automatiza flujos de trabajo y conecta servicios fácilmente usando Make (antes Integromat)."
  cta: "Explorar Make"
  category: "no-code"

# PLATAFORMAS NO-CODE CON IA
- icon: "⚡"
  image: "https://zapier.com/favicon.ico"
  title: "Zapier AI: Automatización inteligente"
  link: "https://zapier.com/ai"
  desc: "Crea automatizaciones complejas usando lenguaje natural con la IA integrada de Zapier."
  cta: "Probar gratis"
  category: "no-code"
- icon: "🧠"
  image: "https://n8n.io/favicon.ico"
  title: "n8n: Automatización open source con IA"
  link: "https://n8n.io/integrations/openai/"
  desc: "Plataforma gratuita y open source para crear workflows automatizados con integración nativa de IA."
  cta: "Descargar"
  category: "open-source"

# ASISTENTES IA PARA TAREAS ESPECÍFICAS
- icon: "📝"
  image: "https://notion.so/favicon.ico"
  title: "Notion AI: Tu segundo cerebro automatizado"
  link: "https://www.notion.so/product/ai"
  desc: "Automatiza la creación de contenido, resúmenes y organización de información en Notion."
  cta: "Ver demos"
  category: "productivity"
- icon: "📊"
  image: "https://www.airtable.com/favicon.ico"
  title: "Airtable AI: Bases de datos inteligentes"
  link: "https://www.airtable.com/platform/ai"
  desc: "Genera fórmulas, categoriza datos y crea insights automáticamente con IA integrada."
  cta: "Explorar"
  category: "data-automation"

# AUTOMATIZACIÓN DE MARKETING CON IA
- icon: "📧"
  image: "https://mailchimp.com/favicon.ico"
  title: "Mailchimp AI: Marketing automation inteligente"
  link: "https://mailchimp.com/features/ai-powered-tools/"
  desc: "Optimiza campañas de email, segmenta audiencias y genera contenido automáticamente."
  cta: "Ver features"
  category: "marketing"
- icon: "📱"
  image: "https://hootsuite.com/favicon.ico"
  title: "Hootsuite OwlyWriter: Content creation automatizado"
  link: "https://www.hootsuite.com/products/owlywriter-ai"
  desc: "Genera posts para redes sociales, captions y hashtags automáticamente con IA."
  cta: "Probar"
  category: "social-media"

# AUTOMATIZACIÓN DE DESARROLLO
- icon: "🔧"
  image: "https://github.com/favicon.ico"
  title: "GitHub Actions + AI: CI/CD inteligente"
  link: "https://github.com/features/actions"
  desc: "Automatiza testing, deployment y code review usando IA en tus pipelines de desarrollo."
  cta: "Ver workflows"
  category: "development"
- icon: "🐛"
  image: "https://www.codacy.com/favicon.ico"
  title: "Codacy: Code review automatizado con IA"
  link: "https://www.codacy.com/"
  desc: "Detecta bugs, vulnerabilidades y code smells automáticamente en cada commit."
  cta: "Analizar código"
  category: "development"

# AUTOMATIZACIÓN DE PROCESOS EMPRESARIALES
- icon: "🏢"
  image: "https://www.uipath.com/favicon.ico"
  title: "UiPath: RPA + IA para empresas"
  link: "https://www.uipath.com/product/ai-powered-automation"
  desc: "Automatiza procesos empresariales complejos combinando RPA con capacidades de IA."
  cta: "Ver casos de uso"
  category: "enterprise"
- icon: "💼"
  image: "https://monday.com/favicon.ico"
  title: "Monday.com AI: Project management inteligente"
  link: "https://monday.com/ai/"
  desc: "Automatiza seguimiento de proyectos, asignación de tareas y reporting con IA."
  cta: "Probar gratis"
  category: "project-management"

# AUTOMATIZACIÓN DE CONTENIDO
- icon: "🎨"
  image: "https://www.canva.com/favicon.ico"
  title: "Canva AI: Diseño automatizado"
  link: "https://www.canva.com/ai-image-generator/"
  desc: "Genera designs, presentaciones y contenido visual automáticamente usando IA."
  cta: "Crear diseño"
  category: "design"
- icon: "🎬"
  image: "https://www.synthesia.io/favicon.ico"
  title: "Synthesia: Videos corporativos automatizados"
  link: "https://www.synthesia.io/"
  desc: "Crea videos de formación y presentaciones con avatares IA en múltiples idiomas."
  cta: "Ver demo"
  category: "video"

# AUTOMATIZACIÓN DE ATENCIÓN AL CLIENTE
- icon: "💬"
  image: "https://www.intercom.com/favicon.ico"
  title: "Intercom AI: Soporte automatizado inteligente"
  link: "https://www.intercom.com/ai"
  desc: "Resuelve consultas de clientes automáticamente con chatbots IA conversacionales."
  cta: "Ver soluciones"
  category: "customer-service"
- icon: "🎧"
  image: "https://www.zendesk.com/favicon.ico"
  title: "Zendesk AI: Tickets inteligentes"
  link: "https://www.zendesk.com/ai/"
  desc: "Categoriza, prioriza y sugiere respuestas para tickets de soporte automáticamente."
  cta: "Explorar AI"
  category: "customer-service"

# AUTOMATIZACIÓN PERSONAL Y PRODUCTIVIDAD
- icon: "🗓️"
  image: "https://calendly.com/favicon.ico"
  title: "Calendly AI: Scheduling inteligente"
  link: "https://calendly.com/"
  desc: "Optimiza tu calendario y automatiza la programación de reuniones con IA."
  cta: "Configurar"
  category: "productivity"
- icon: "📋"
  image: "https://www.otter.ai/favicon.ico"
  title: "Otter.ai: Transcripciones automáticas"
  link: "https://otter.ai/"
  desc: "Transcribe reuniones automáticamente y genera resúmenes ejecutivos con IA."
  cta: "Probar gratis"
  category: "productivity"
